language: java
jdk: oraclejdk7
env:
  global:
    secure: "LwfuqPbxvBZfeAZvq6VdaBo/43N1rkW7yK1sCOF7EFpT42WB6WPll/ppeCaIIjB56kEzbL7WLGc01z/gZj3yjj0ovDtUX2AqURxQUJIrz0ApOlz9wNqjpI/m3xJ4bLpgNL7iNAPru6z/JjA5YlNfAxWOVym1+luiUbjieS6B8cg="
after_success:
  - .travis-tools/javadoc.sh
